### ISSUE TITLE
License type

### ISSUE THREAD

**Issue by jpizarrom** [ildoonet/tf-pose-estimation#163]
Hi,
@ildoonet thank for sharing.

It will be very helpful to know if you had used code of [1][5][6],  their license is "ACADEMIC OR NON-PROFIT ORGANIZATION NONCOMMERCIAL RESEARCH USE ONLY" [2], and your project is under "Apache License 2.0" [3].

I am asking because I want to port your project [4] to Android Using SNPE SDK, therefore I want to know which l license should I use.

[1] https://github.com/CMU-Perceptual-Computing-Lab/openpose
[2] https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/LICENSE#L3
[3] https://github.com/ildoonet/tf-pose-estimation/blob/master/LICENSE
[4] https://github.com/ildoonet/tf-pose-estimation
[5] https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation
[6] https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose

**Comment by jpizarrom** [comment]
In [1] and [2] they changed the licenses from GPL to other.

[1] https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose/commit/122d9dbb9a72150e777af1fafaf29f99617a3311#diff-9879d6db96fd29134fc802214163b95a
[2] https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose/commit/122d9dbb9a72150e777af1fafaf29f99617a3311#diff-9879d6db96fd29134fc802214163b95a

**Comment by jpizarrom** [comment]
Thanks for sharing

**Comment by s101010tw** [comment]
Hi @jpizarrom, 
Sorry, I have one question about Android SNPE SDK, 
Did you successfully port the project [4] to Android using SNPE SDK?
If yes, how about the performance (FPS)?

Thanks

**Comment by kristijanbartol** [comment]
Is it therefore OK to use the mobilethin model for commercial use in an Android app?

**Comment by kartikeyporwal** [comment]
> I didn't used [1]'s codes but the model named cmu is copied from theirs.
> 
> [5]'s codes were very helpful, but I implemented in a different way and in a different language. But it is somewhat similar.
> 
> I didn't used [6]'s codes.

Hi, nice work!!

Since you added license type as commercial but used CMU's Caffe Model and converted to Tensorflow model. But, we can't use their pretrained model which follows the same license as their code, [this](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1444) is the issue, I'm referring to.

Converting CMU's pretrained model is a derivative of their work, so it's owned by CMU based on the [license of openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/e086e6fc6a5f4650d5c3a100b8ced8363fd2d099/LICENSE#L20). Could you look [this issue](https://github.com/CMU-Perceptual-Computing-Lab/openpose/pull/321) from [OpenPose](https://github.com/CMU-Perceptual-Computing-Lab/openpose/)  repo for more detail?

Though I'm uncertain about your mobilenet models.

So, this or any other implementation of Openpose can't be used commercially for free!

What do you think about this?
