### ISSUE TITLE
NameError: name 'ast' is not defined, AttributeError: 'TfPoseEstimator' object has no attribute 'persistent_sess'

### ISSUE THREAD

**Issue by daimingzhong** [ildoonet/tf-pose-estimation#58]
I ran with the following command:
```
python3 run.py --model=mobilenet_thin_432x368
```
 under python 3.6.3 on Mac with the following information:
``` 
RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)

NameError: name 'ast' is not defined
```
After I changed to
```
scales = args.scales
```
it generated another error.
```
AttributeError: 'TfPoseEstimator' object has no attribute 'persistent_sess'
```
I am not sure if it is my environment problem. Could anyone help me? Thank you in advance!

**Comment by rludlow** [comment]
Changing scales to `arg.scales` successfully addressed the first problem you had, so the next error you're encountering is unrelated and you're it seeing now because you're able to get further through the code.

It does appear to be an environment issue. I faced the same problem before. I'd recommend running the program with `python3.5 run.py` and `python3.6 run.py` instead of `python3 run.py` and seeing if either works. If not, then I'd recommend making sure you're in an environment running python3.6 and then reinstall (and upgrade) tensorflow. This may be helpful: https://github.com/lakshayg/tensorflow-build

**Comment by anewway** [comment]
I've encountered the same problem, and solved it by the following modifications.


For the second error:
```
AttributeError: 'TfPoseEstimator' object has no attribute 'persistent_sess'
```

First go to the project root directory, and re-run the command again.

And remember that you have gone to parent directory, so you need to fix the script path

from
```
python3 run.py
```
to 
```
python3 src/run.py
```

The reason is that the run.py is not in root directory, but the model using relative path to root. If you run the script in src/, it can't find the model.

Hope it helps.

**Comment by ildoonet** [comment]
@daimingzhong Can you try again with the latest version? Please pull sources and run it again.

Also, second problem is related model files. You need to download model files. please follow the instruction on README.

**Comment by daimingzhong** [comment]
Thank you so much! I forgot to follow. I will let you know the updates soon.
