### ISSUE TITLE
About train coco dataset with Negative samples

### ISSUE THREAD

**Issue by segatecm** [ildoonet/tf-pose-estimation#66]
Hi @ildoonet, I have a trainning question about the coco.
there are many no Person pics in coco, do you use them as negative samples or just ignore them?

**Comment by ildoonet** [comment]
@segatecm I used them as a negative samples.

**Comment by segatecm** [comment]
thanks,
I have another question about the negative samples. There are just some empty heatmaps and vecmaps, Filled with zero value?  is my idea right?

**Comment by ildoonet** [comment]
@segatecm Yes, that is correct. Since there are nothings to predict, no joints and no relationships between joints. But, in my personal opinion, it needs more data on negative set as well as positive set if this model needs to be improved. I'm also thinking about this.

If you are satisfied and get all answers, please close this issue.

**Comment by segatecm** [comment]
Thank you!
