### ISSUE TITLE
Run tf-openpose on Jetson TX1 or Jetson TK1.

### ISSUE THREAD

**Issue by gelez** [ildoonet/tf-pose-estimation#77]
Hi everyone!
I am trying to run the tf-openpose with mobilenet on Jetson TX1 and Jetson TK1 boards. I just decided to do that.
Could you share your experience of installation? 
Should I install latest tensorflow and OpenCV?

**Comment by ouceduxzk** [comment]
use jetpack from nvidia

**Comment by gelez** [comment]
Hello @ouceduxzk . I am already installed JetPack 3.1. 
But it does not contain tensorflow. OpenCV is also outdated.
The Jetpack 3.2 now only for Jetson TX2 board. 
Could you share your experience of installation? Just steps what should I do.

Yesterday, I'm googled the solution and do not found the tensorflow 1.5 or 1.4 for python 3.5 for jetson TX1 or TK1 boards.
According to the jetsonhacks now I should recompile the kernel and than rebuild the tensorflow.  https://github.com/jetsonhacks/installTensorFlowTX1
The same is for OpenCV. http://www.jetsonhacks.com/2017/09/05/build-opencv-on-the-nvidia-jetson-tx1/

I know that first "openpose" was builded on caffe. But it is so slow. I want the fastest solution for pose detection.

**Comment by ildoonet** [comment]
@gelez I just installed tensorflow and opencv using JetsonHacks's solution. And I used JetsonTX2. I guess you need to follow the instruction, since it is a more reliable source than my experience.

Also, this is not a relevant issue for this repository(more related to jetson or tensorflow), I'm closing this.
