### ISSUE TITLE
Step by step explanation for Model Optimization for Inference

### ISSUE THREAD

**Issue by MohameHassan** [ildoonet/tf-pose-estimation#98]
Can someone please provide more detailed instructions for optimizing the model for Inference?
I have tried to follow the instructions in https://github.com/ildoonet/tf-pose-estimation/blob/master/etcs/training.md#model-optimization-for-inference
But many steps are not obvious to me. I have succesfully retrained the CMU model but am not sure how to move on:
1- How to use `run_checkpoint.py`? how can I point it to my new trained model?
2- Can you provide an example for the parameters to graph freezing step
```
$ python3 -m tensorflow.python.tools.freeze_graph \
  --input_graph=... \
  --output_graph=... \
  --input_checkpoint=... \
  --output_node_names="Openpose/concat_stage7"
```
3- How to use bazel? should i rebuild the whole tensorflow from source? when i tried this command ` bazel build tensorflow/tools/graph_transforms:transform_graph` I got empty bazel-bin folder

**Comment by elmuz** [comment]
Hi,
from what I understood a common pipeline would be the following.

1. You train your model and periodically save some checkpoints
2. When you are ready to optimize your model for deployment export the graph and checkpoint like in run_checkpoint.py:
```
tf.train.write_graph(sess.graph_def, '/tmp', my_model-graph.pbtxt', as_text=True)
graph = tf.get_default_graph()
dir(graph)
saver = tf.train.Saver()
saver.save(sess, '/tmp/chk', global_step=last_step)
```
By doing this in '/tmp' you will have a pbtxt file and a checkpoint. The former is the description (in text form) of your model, like which nodes are present, their names, dimensions, input/output connections and so on. The latter is a contains the weights for all variables.

3. Now you can run the optimization by executing the 'freeze_graph' script. This program needs to know the shape of your model (pbtxt), the weights for all variables (checkpoint), plus the output nodes. By going backward from the output, it can delete some nodes that are not needed anymore (like all the gradient operations), leaving only the necessary operations. It also convert variables to constants in order to reduce the final footprint.
In my case I run something like this:
`bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=/tmp/my_model-graph.pbtxt --input_checkpoint=/tmp/chk-1 --output_graph=/tmp/my_model-frozen_graph.pb --output_node_names=probabilities`
In my case 'probabilities' is the name of the Softmax operation, `probabilities = tf.nn.softmax(logits, name='probabilities')`, while '--output_graph' is what you finally need for inference/prediction.

To use bazel you need to build some parts of TensorfFow by hand. Nothing really complicated. In case you installed TensorFlow using pip/pip3, just clone the github repository somewhere on your disk. From the root repository folder run `bazel build tensorflow/python/tools:freeze_graph -c opt --copt=-msse4` and wait for a while. When it finishes you can run `bazel-bin ...` command from above.

I hope it helps somehow...

**Comment by MohameHassan** [comment]
Thanks a lot, that's really helpful.
I am just confused about the run_checkpint.py script. 
If I got it correctly then I should use similar commands inside my training code to generate the graph(pbtxt) and the check points. I should not run it by itself. Right?

**Comment by MohameHassan** [comment]
Also do you have any information about the graph transform step. Especially this argument
strip_unused_nodes(type=float, shape="1,368,368,3")

Because when I followed similar steps to what is descrped above, I got a graph where the nodes have no species shape, the output node for example is of shape (?,?,?,57) and that led to many errors

**Comment by JakubWojciechowski** [comment]
The run_checkpoint.py script works, you only have to:
1. Correct the path to the model in networks.py (`ckpts` directory)
2. If you have a problem with spatial shape, block it in run_checkpoint.py, line 25, e.g. 
`input_node = tf.placeholder (tf.float32, shape = (None, 368, 432, 3), name = 'image')`

**Comment by zjbabylove** [comment]
@ildoonet @elmuz 
Hi, I skip the train.py step, and I download the mobilenet checkpoint file that author provided, its including three files: model-388003.data-00000-of-000、 model-388003.index、 model-388003.meta，I expect to get the final optimized model file: graph.pb,  what steps can I do？

**Comment by zjbabylove** [comment]
I try to run the run_checkpoint.py script like that： "python3 run_checkpoint.py --model=mobilenet_fast", but I got an error:
Traceback (most recent call last):
  File "run_checkpoint.py", line 27, in <module>
    net, _, last_layer = get_network(args.model, input_node, sess, trainable=False)
  File "/home/cyj/cyj/pose/tf-openpose/tf_pose/networks.py", line 24, in get_network
    net = MobilenetNetwork({'image': placeholder_input}, conv_width=0.5, conv_width2=0.5, trainable=trainable)
  File "/home/cyj/cyj/pose/tf-openpose/tf_pose/network_mobilenet.py", line 13, in __init__
    network_base.BaseNetwork.__init__(self, inputs, trainable)
  File "/home/cyj/cyj/pose/tf-openpose/tf_pose/network_base.py", line 63, in __init__
    self.setup()
  File "/home/cyj/cyj/pose/tf-openpose/tf_pose/network_mobilenet.py", line 39, in setup
    (self.feed('Conv2d_7').upsample(2, name='Conv2d_7_upsample'))
  File "/home/cyj/cyj/pose/tf-openpose/tf_pose/network_base.py", line 38, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/home/cyj/cyj/pose/tf-openpose/tf_pose/network_base.py", line 168, in upsample
    return tf.image.resize_bilinear(input, [int(input.get_shape()[1]) * factor, int(input.get_shape()[2]) * factor], name=name)
TypeError: __int__ returned non-int (type NoneType)

How to fix it?

**Comment by zjbabylove** [comment]
I have followed the steps, and modify the run_checkpoint.py file
input_node = tf.placeholder(tf.float32, shape=(None, None, None, 3), name='image')
to
input_node = tf.placeholder(tf.float32, shape=(None, 368, 432, 3), name='image')

then run:
$ python3 run_checkpoint.py --model=mobilenet

and I got en error:
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1,1,128,19] rhs shape= [1,1,64,19]
[[Node: save/Assign_293 = Assign[T=DT_FLOAT, _class=["loc:@Openpose/MConv_Stage5_L2_5_pointwise/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Openpose/MConv_Stage5_L2_5_pointwise/weights, save/RestoreV2/_587)]]
[[Node: save/RestoreV2/_32 = _SendT=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_38_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"]]

how to fix this error?
